# Generated by Django 4.2.19 on 2025-03-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, null=True, verbose_name="Телеграм пользователя"
            ),
        ),
    ]
